### ISSUE TITLE
No reviews appear in mobile app

### ISSUE THREAD

**Issue by hungriesthippo** [akrivka/roamsr#12]

**Comment by akrivka** [comment]
Works on mine (Android). Possible it doesn't work on Apple devices. Can you provide more info?

**Comment by hungriesthippo** [comment]
Yes, it is iOS . Same problem in either the PWA or from Chrome app. The review button appears but shows 0 0.

**Comment by hungriesthippo** [comment]
I've been seeing some reviews lately. But the number is different than on desktop.

**Comment by akrivka** [comment]
Let me know if it works now.

**Comment by hungriesthippo** [comment]
Seems to be working. Yay!
