### ISSUE TITLE
Blocks at the bottom of the page are unclickable

### ISSUE THREAD

**Issue by hungriesthippo** [akrivka/roamsr#14]
After "show answer", I sometimes have many blocks, which extend to the bottom of the page. In this case, I can't click the blocks where they intersect with the button area. Could possibly be fixed by adding some margin at the bottom of the appropriate div.

**Comment by akrivka** [comment]
Not sure... The response area is just plonked on top of everything. Better practice would be not having so many blocks. :D Will consider though.
