### ISSUE TITLE
New review items not showing up after a few days (Firefox)

### ISSUE THREAD

**Issue by apellis** [akrivka/roamsr#18]
I have a few dozen cards created using roamsr. The first two days I used the system, it worked as expected. Starting yesterday or the day before, I've noticed the following erroneous behavior:

When I click on either clickable portion of the roamsr UI ("start review" or the blue and green numbers), nothing happens. Both the blue and green numbers are 0 and have been for a few days. Today, that's because the [[roam/sr/review]] block in my daily notes is empty, and it's empty because I wasn't able to review yesterday or the day before.

Yesterday (Feb 17)'s [[roam/sr/review]] block has several items in it, all with #sr as a suffix. For Feb 16's [[roam/sr/review]] block, I see a mix of #sr and #sr #r/3, indicating that some review items were processed and others weren't.

The above behavior is on up to date Firefox (84.0.2) running on Mac OS 10.15.5. On Chrome (88.0.4324.150), everything works as expected. I do not see any JS console errors or warnings when trying to use Roam or roamsr.

**Comment by akrivka** [comment]
vtf, this is Chrome:

![image](https://user-images.githubusercontent.com/26225771/108417548-65644980-7230-11eb-83bd-76ca20bcbabc.png)

and this is Firefox:

![image](https://user-images.githubusercontent.com/26225771/108417604-790fb000-7230-11eb-8c8b-02cf222a39a6.png)

It's probably at the root of the problem. Will fix soon.

**Comment by apellis** [comment]
Thanks for the rapid fix! It's working for me now.
