### ISSUE TITLE
TypeError: Cannot read property 'uid' of undefined (in roamsr.loadState)

### ISSUE THREAD

**Issue by csvoss** [akrivka/roamsr#30]
roam/sr was working amazingly for me this morning until at some point I refreshed my Roam and I noticed that roam/sr wasn't loading anymore. There is no "Review" element in the sidebar, and in my console I'm getting the following error message:

![image](https://user-images.githubusercontent.com/3229696/110210696-c9bb1600-7e8a-11eb-84f1-5ea95ef447bd.png)

error as plaintext:

```
stable.js:201 Uncaught (in promise) TypeError: Cannot read property 'uid' of undefined
    at stable.js:201
    at Array.some (<anonymous>)
    at isNew (stable.js:200)
    at stable.js:247
    at Array.map (<anonymous>)
    at Object.roamsr.loadCards (stable.js:243)
    at async Object.roamsr.loadState (stable.js:607)
```

It's almost certainly due to some new card block I introduced somewhere, but sadly I don't know exactly how or which one in order to narrow it down.

Thanks for this amazing extension!

**Comment by csvoss** [comment]
digging into the stack trace, it looks like some `review`'s `.page` attribute must be undefined:

```
  var isNew = (res) => {
    return res._refs ? !res._refs.some(review => {
      var reviewDate = new Date(roamsr.getFuckingDate(review.page.uid));
      reviewDate.setDate(reviewDate.getDate() + 1);
      return reviewDate < dateBasis;
    }) : true
  };
```

**Comment by akrivka** [comment]
(omg hi Chelsea do you remember me from SPARC?)

I'm in the road currently, but I think you should try investigating orphans (by writing {{orphans}} in some block). 

Will get back to you later.

**Comment by csvoss** [comment]
(hiii! I do!! and I am absolutely loving these plugins)

Thanks! I'd noticed a couple of times in the past that I was seeing the occasional mysterious Roam page that I found difficult to delete – so even if it doesn't end up helping with roam/sr, I appreciate the tip on how to deal with those. I did actually see a mysterious undeletable page earlier today, so that orphaned page may well be responsible.

edit: orphaned blocks, not orphaned pages!

**Comment by csvoss** [comment]
Yep, it was an orphaned `#sr` block! Thanks a bunch - all fixed!

**Comment by brunoeducsantos** [comment]
Hi @csvoss ,
How did you find the orphaned block?
Thanks

**Comment by csvoss** [comment]
As Adam mentions above: write {{orphans}} somewhere in some block of your Roam graph.

Cheers!

**Comment by brunoeducsantos** [comment]
Thanks @csvoss  ! Although the Review doesnt show on the side bar yet :(
